[package]
name = "nft"
edition = "2024.beta"
license = "MIT"
authors = [
  "Carl Klöfverskjöld (www.github.com/Reblixt)",
]
version = "1"

[dependencies]
# Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/mainnet", override = true }
# access_control = { git = "https://github.com/Reblixt/Sui-Access-Control.git", rev = "main" }
# Kiosk = { git = "https://github.com/MystenLabs/apps.git", subdir = "kiosk", rev = "main" }
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet", override = true }
# access_control = { git = "https://github.com/Reblixt/Sui-Access-Control.git", rev = "testnet" }
# Kiosk = { git = "https://github.com/MystenLabs/apps.git", subdir = "kiosk", rev = "testnet" }


[addresses]
nft = "0x2a2ede7a4600c8e6870344dbf7d1a874a35a34a0cda06c0791a7db73b606489f"
# Registry = "0x1fff6743212f9d1ba37064dbc1469b9c7454ffbd6ff9a79abcc189b450f5f551"
# UpgradeCap = "0xb7e2c11ce850e117a7738af78c65c745fc532382e54d59043155180d363f8783"


[dev-dependencies]
# The dev-dependencies section allows overriding dependencies for `--test` and
# `--dev` modes. You can introduce test-only dependencies here.
# Local = { local = "../path/to/dev-build" }

[dev-addresses]
# The dev-addresses section allows overwriting named addresses for the `--test`
# and `--dev` modes.
# alice = "0xB0B"
